/*
 * Peter Horne-Deus
 * AverageCalculator.java
 * This program calculates your average from 4 grades
 * October 3, 2018
 */

/**
 *
 * @author pehor9164
 */
import java.text.DecimalFormat;
public class AverageCalculator extends javax.swing.JFrame {

    
    
    public AverageCalculator() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        averageCalculatorPanel = new javax.swing.JPanel();
        gradeOneTxt = new javax.swing.JTextField();
        gradeFourTxt = new javax.swing.JTextField();
        gradeTwoTxt = new javax.swing.JTextField();
        gradeThreeTxt = new javax.swing.JTextField();
        gradeFourLabel = new javax.swing.JLabel();
        gradeOneLable = new javax.swing.JLabel();
        gradeTwoLable = new javax.swing.JLabel();
        gradeThreeLabel = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();
        titleLable = new javax.swing.JLabel();
        instructionsLable = new javax.swing.JLabel();
        averageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        averageCalculatorPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gradeOneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeOneTxtActionPerformed(evt);
            }
        });
        averageCalculatorPanel.add(gradeOneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 54, -1));

        gradeFourTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeFourTxtActionPerformed(evt);
            }
        });
        averageCalculatorPanel.add(gradeFourTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 54, -1));

        gradeTwoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeTwoTxtActionPerformed(evt);
            }
        });
        averageCalculatorPanel.add(gradeTwoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 54, -1));

        gradeThreeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeThreeTxtActionPerformed(evt);
            }
        });
        averageCalculatorPanel.add(gradeThreeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 54, -1));

        gradeFourLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gradeFourLabel.setText("Grade 4");
        averageCalculatorPanel.add(gradeFourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 50, -1));

        gradeOneLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gradeOneLable.setText("Grade 1");
        averageCalculatorPanel.add(gradeOneLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 50, -1));

        gradeTwoLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gradeTwoLable.setText("Grade 2");
        averageCalculatorPanel.add(gradeTwoLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, -1));

        gradeThreeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gradeThreeLabel.setText("Grade 3");
        averageCalculatorPanel.add(gradeThreeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        averageCalculatorPanel.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        titleLable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLable.setForeground(new java.awt.Color(255, 51, 51));
        titleLable.setText("Course Mark Calculator");
        averageCalculatorPanel.add(titleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 220, 20));

        instructionsLable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        instructionsLable.setText("Enter you four grades and press calculate");
        averageCalculatorPanel.add(instructionsLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, -1));

        averageLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        averageLabel.setText("Your Average Is: ");
        averageCalculatorPanel.add(averageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(averageCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(averageCalculatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gradeOneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeOneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeOneTxtActionPerformed

    private void gradeFourTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeFourTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeFourTxtActionPerformed

    private void gradeTwoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeTwoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeTwoTxtActionPerformed

    private void gradeThreeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeThreeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeThreeTxtActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        
        //Variables
        double grade1,grade2,grade3,grade4,average;
        
        grade1 = Double.parseDouble(gradeOneTxt.getText());
        grade2 = Double.parseDouble(gradeTwoTxt.getText());
        grade3 = Double.parseDouble(gradeThreeTxt.getText());
        grade4 = Double.parseDouble(gradeFourTxt.getText());
        
        //Creating Decimal Format 
        DecimalFormat rounded = new DecimalFormat("###,###.##");
        
        //Calculation algerithem and rounding allgerithem
        average = (grade1 + grade2 + grade3 + grade4)/4;   
        //Output
        averageLabel.setText("Your Average Is " + rounded.format(average));
        
        //Reseting calculator 
        gradeOneTxt.setText(" ");
        gradeTwoTxt.setText(" ");
        gradeThreeTxt.setText(" ");
        gradeFourTxt.setText(" ");
    }//GEN-LAST:event_calculateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AverageCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AverageCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel averageCalculatorPanel;
    private javax.swing.JLabel averageLabel;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel gradeFourLabel;
    private javax.swing.JTextField gradeFourTxt;
    private javax.swing.JLabel gradeOneLable;
    private javax.swing.JTextField gradeOneTxt;
    private javax.swing.JLabel gradeThreeLabel;
    private javax.swing.JTextField gradeThreeTxt;
    private javax.swing.JLabel gradeTwoLable;
    private javax.swing.JTextField gradeTwoTxt;
    private javax.swing.JLabel instructionsLable;
    private javax.swing.JLabel titleLable;
    // End of variables declaration//GEN-END:variables
}
